# Generated by Django 6.0.6 on 2026-09-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, default='Company', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('image', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('author_role', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('read_time', models.IntegerField(default=3)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-featured', '-date', '-created_at'],
            },
        ),
    ]
