# Generated by Django 6.0.6 on 2026-09-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='e.g. ch1, ch2, ch3', max_length=40, unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_tet', models.CharField(blank=True, max_length=200)),
                ('body_en', models.TextField()),
                ('body_tet', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Chapter',
                'verbose_name_plural': 'About Chapters',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_url',
            field=models.CharField(blank=True, help_text='Static path or URL, e.g. images/team/Acacio.jpg', max_length=500),
        ),
    ]
